name: Create and publish a Docker image to GHCR

on:
  push:
    paths:
      - ".github/workflows/docker.yml"
      - "Dockerfile"
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/docker.yml"
      - "Dockerfile"

env:
  REGISTRY: ghcr.io
  PLATFORMS: linux/amd64,linux/arm64
  VERSION: "1.4.1"
  VERSION_MINOR: "1.4"
  VERSION_MAJOR: "1"


jobs:
  build:
    name: Build for ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: alpine
            context: stable/alpine/default/release
            tags: |
              type=raw,value=latest,enable={{is_default_branch}}
              type=raw,value=alpine,enable={{is_default_branch}}
          - name: alpine-debug
            context: stable/alpine/default/debug
            tags: |
              type=raw,value=debug,enable={{is_default_branch}}
              type=raw,value=debug-alpine,enable={{is_default_branch}}
          - name: alpine-modules
            context: stable/alpine/modules/release
            tags: |
              type=raw,value=modules,enable={{is_default_branch}}
              type=raw,value=modules-alpine,enable={{is_default_branch}}
          - name: alpine-modules-debug
            context: stable/alpine/modules/debug
            tags: |
              type=raw,value=modules-debug,enable={{is_default_branch}}
              type=raw,value=modules-debug-alpine,enable={{is_default_branch}}
          - name: debian
            context: stable/debian/default/release
            tags: |
              type=raw,value=debian,enable={{is_default_branch}}
          - name: debug-debian
            context: stable/debian/default/debug
            tags: |
              type=raw,value=debug-debian,enable={{is_default_branch}}
          - name: modules-debian
            context: stable/debian/modules/release
            tags: |
              type=raw,value=modules-debian,enable={{is_default_branch}}
          - name: modules-debug-debian
            context: stable/debian/modules/debug
            tags: |
              type=raw,value=modules-debug-debian,enable={{is_default_branch}}
          - name: ubuntu
            context: stable/ubuntu/default/release
            tags: |
              type=raw,value=ubuntu,enable={{is_default_branch}}
          - name: debug-ubuntu
            context: stable/ubuntu/default/debug
            tags: |
              type=raw,value=debug-ubuntu,enable={{is_default_branch}}
          - name: modules-ubuntu
            context: stable/ubuntu/modules/release
            tags: |
              type=raw,value=modules-ubuntu,enable={{is_default_branch}}
          - name: modules-debug-ubuntu
            context: stable/ubuntu/modules/debug
            tags: |
              type=raw,value=modules-debug-ubuntu,enable={{is_default_branch}}
          - name: centos
            context: stable/centos/default/release
            tags: |
              type=raw,value=centos,enable={{is_default_branch}}
          - name: debug-centos
            context: stable/centos/default/debug
            tags: |
              type=raw,value=debug-centos,enable={{is_default_branch}}
          - name: modules-centos
            context: stable/centos/modules/release
            tags: |
              type=raw,value=modules-centos,enable={{is_default_branch}}
          - name: modules-debug-centos
            context: stable/centos/modules/debug
            tags: |
              type=raw,value=modules-debug-centos,enable={{is_default_branch}}

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: ${{ matrix.tags }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ matrix.context }}
          provenance: false
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max